config/routes.rb
Rails.application.routes.draw do
  get 'todos/index', to: 'todos#index', as: 'todos_index'
  get 'todos/:id', to: 'todos#show', as: 'todos_show'
  patch 'todos/:id', to: 'todos#update', as: 'todo'
  
  devise_for :users
  get 'tasks/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "tasks#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  has_many:todos
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :user
  belongs_to :task
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many:todos

  def count_task
    todos.where(status: true).count
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks=Task.all
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
before_action :authenticate_user!

  def index
    @todos=  current_user.todos.all
  end

  def show
    @todo=Todo.find(params[:id])
    @all=Todo.where(task: @todo.task, status:true).count
    @all_person=Todo.where(task: @todo.task, status:true)
  end

  def update
    @todo=Todo.find(params[:id])
    @todo.status =! @todo.status
    @todo.save
    redirect_to todos_index_path
  end

private

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Aa</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class='m-3 p-3'>
    <%= render 'sharred/nav' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/sharred/_nav.html.erb
<!-- Image and text -->
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand" href="#">
    <img src="/docs/4.5/assets/brand/bootstrap-solid.svg" width="30" height="30" class="d-inline-block align-top" alt="" loading="lazy">
    <ul>
    <% if user_signed_in?%>
    <li>Hola, <%= current_user.email %>
    <span>hisiste </span>
    <%= current_user.count_task %>
    <span>de 3</span>  
    <%= link_to 'Cerrar_sesion', destroy_user_session_path, method: :delete %>
    </li>
    <% end %>
    </ul>
  </a>
</nav>

app/views/tasks/index.html.erb
<% @tasks.each_slice(3) do |task2| %>
<div class="card-deck">
<%task2.each do |task| %>
  <div class="card">
    <%= image_tag task.photo , class: 'card-image-top img-fluid', style: 'height:250px;width:250px', style: "filter: grayscale(100%)"  %>
    <div class="card-body">
      <h5 class="card-title"> <%= task.name %></h5>
      <%= link_to 'detaile', todos_show_path(task), class:"btn btn-dark" %>
      <%=link_to "listo", todos_index_path, class:"btn btn-outline-danger" %>
      <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
    </div>
  </div>
<% end %>
</div>
<% end %>

app/views/todos/index.html.erb
<% @todos.each_slice(3) do |todo2| %>
<div class="card-deck">
<%todo2.each do |todo| %>
  <div class="card">
     <% if todo.status == true %>
        <%= image_tag todo.task.photo , class: 'card-image-top img-fluid', style: 'height:250px;width:250px'  %>
    <% else %>
        <%= image_tag todo.task.photo , class: 'card-image-top img-fluid', style: 'height:250px;width:250px', style: "filter: grayscale(100%)"  %>
    <% end %>
    <div class="card-body">
      <h5 class="card-title"> <%= todo.task.name %></h5>
      <%= link_to 'detaile', todos_show_path(todo), class:"btn btn-dark" %>

       <% if todo.status == true %>
        <%=link_to "No listo", todo_path(todo),method: :patch, class:"btn btn-outline-success" %>
      <% else %>
        <%=link_to "listo", todo_path(todo),method: :patch, class:"btn btn-outline-danger" %>
      <% end %>
      <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
    </div>
  </div>
<% end %>
</div>
<% end %>

app/views/todos/show.html.erb
<div class="card">
   <% if @todo.status == true %>
      <%= image_tag @todo.task.photo , class: 'card-image-top ', style: 'width:200px'  %>
  <% else %>
      <%= image_tag @todo.task.photo , class: 'card-image-top ', style: 'width: 200px', style: "filter: grayscale(100%)"  %>
  <% end %>
  <div class="card-body">
    <h5 class="card-title"> <%= @todo.task.name %></h5>

     <% if @todo.status == true %>
      <%=link_to "No listo", todo_path(@todo),method: :patch, class:"btn btn-outline-success" %>
    <% else %>
      <%=link_to "listo", todo_path(@todo),method: :patch, class:"btn btn-outline-danger" %>
    <% end %>
    <p class="card-text"><small class="text-muted">Lo hisieron tmb <%= @all %> </small></p>
    <% @all_person.each do |person| %>
    <%= person.user.email %>
    <%end %>
  </div>
</div>
<
<%= link_to 'Back', todos_index_path %>